export type ProductKey =
  | "teamviewer-remote"
  | "teamviewer-tensor"
  | "teamviewer-frontline"
  | "teamviewer-assist-ar"
  | "teamviewer-remote-management"
  | "teamviewer-dex";

export type JobType = "debug" | "troubleshoot";

export type JobStatus = "queued" | "running" | "completed" | "failed" | "cancelled";

export type AgentName =
  | "product-gatekeeper"
  | "session-context"
  | "diagnosis-planner"
  | "connectivity"
  | "auth-policy"
  | "endpoint-health"
  | "log-intelligence"
  | "remediation"
  | "confidence-escalation"
  | "report";

export interface RootCauseCandidate {
  title: string;
  score: number;
  rationale: string;
  /**
   * True when this candidate was produced by a probe (anchored to a concrete
   * observation: a log signature, a failed connectivity check, etc). False/
   * undefined when it was generated by the LLM. Unanchored LLM candidates that
   * share no content with the collected evidence are dropped as speculation.
   */
  evidenceAnchored?: boolean;
}

export interface ActionItem {
  step: string;
  risk: "low" | "medium" | "high";
  rollback: string;
  /** Optional ready-to-run, OS-native command extracted for copy-paste. */
  command?: string;
}

export interface AgentExecution {
  name: AgentName;
  status: "completed" | "failed" | "skipped";
  note: string;
}

export interface WorkflowReport {
  summary: string;
  hypotheses: string[];
  evidence: string[];
  rootCauses: RootCauseCandidate[];
  actions: ActionItem[];
  confidence: number;
  escalation: {
    required: boolean;
    reason: string;
  };
  execution: AgentExecution[];
  /** Human label of where the probes actually ran (e.g. "local", "ssh user@host",
   *  "azure-vm rg/vm", "k8s ns/pod"). Set by the worker/oneShot wrapper after the
   *  workflow completes; absent on reports built before the ExecutionContext refactor. */
  executionTarget?: string;
  /** Knowledge-base passages retrieved (LanceDB hybrid) and injected into the
   *  specialist prompts. Surfaced in the rendered report as a References section
   *  so the user can verify which KB pages grounded each specialist's reasoning.
   *  STRONG tier only (relevance >= REFERENCE_STRONG_FLOOR). */
  references?: Array<{ title?: string; source: string; topic: string; relevance?: number }>;
  /** Lower-confidence KB articles that are on-topic enough to be worth a look but
   *  did not clear the strong relevance floor. Rendered in a separate "Related
   *  articles" section so they never get mixed with the strong supporting set. */
  relatedReferences?: Array<{ title?: string; source: string; topic: string; relevance?: number }>;
  /** Concrete log sources the log probe actually read on the target (file paths,
   *  the macOS unified-log command, kubectl/journalctl invocations, ...). Surfaced
   *  in the rendered report so the user can see exactly which logs were consulted.
   *  Cross-platform: works for macOS, Windows, Kubernetes and cloud VMs. */
  logSources?: Array<{ source: string; detail?: string }>;
}

export interface JobInput {
  target: string;
  issue: string;
  context?: string;
  /** Optional SSH connection details. When present, all probes execute on
   *  the remote host via SSH instead of locally. */
  connection?: {
    user: string;
    port?: number;
    /** Path to a private key file (otherwise the SSH agent / default key is used). */
    identity?: string;
  };
}

export interface AgentJob {
  id: string;
  product: ProductKey;
  type: JobType;
  status: JobStatus;
  createdAt: string;
  updatedAt: string;
  input: JobInput;
  output?: string;
  report?: WorkflowReport;
  error?: string;
  pid?: number;
  startedAt?: string;
  completedAt?: string;
}
